"""Work items, reminder schedules and reliable source events.

Revision ID: 48b7a65dc109
Revises: 2c638fa481b9
"""
from alembic import op
import sqlalchemy as sa

revision = '48b7a65dc109'
down_revision = '2c638fa481b9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('preset_key', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('due_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_key')
    )
    op.create_index('ix_task_rule_owner', 'task_rules', ['owner_id', 'created_at'], unique=False)
    op.create_table('task_rule_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_date', sa.Date(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exhausted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['task_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'revision')
    )
    op.create_index('ix_rule_schedule_cursor', 'task_rule_schedules', ['next_run_at', 'cursor_date'], unique=False)
    op.create_index(op.f('ix_task_rule_schedules_rule_id'), 'task_rule_schedules', ['rule_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_key', sa.String(length=180), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_number', sa.String(length=60), nullable=False),
    sa.Column('action_kind', sa.String(length=30), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('follow_source', sa.Boolean(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.Column('notified_version', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_reason', sa.String(length=200), nullable=False),
    sa.Column('source_ship_date', sa.Date(), nullable=True),
    sa.Column('source_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','completed','cancelled')"),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['task_rules.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_index('ix_task_delivery', 'tasks', ['status', 'due_at'], unique=False)
    op.create_index('ix_task_owner_status_due', 'tasks', ['assignee_id', 'status', 'due_at'], unique=False)
    op.create_index('ix_task_source', 'tasks', ['source_kind', 'source_id'], unique=False)
    op.create_index('ix_task_store_status_due', 'tasks', ['store_id', 'status', 'due_at'], unique=False)
    op.create_index(op.f('ix_tasks_rule_id'), 'tasks', ['rule_id'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_history_time', 'task_history', ['task_id', 'created_at'], unique=False)
    op.create_table('task_source_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_event_pending', 'task_source_events', ['processed_at', 'created_at'], unique=False)
    op.create_index('ix_task_event_source', 'task_source_events', ['source_kind', 'source_id'], unique=False)
    op.create_table('task_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_notices',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('notification_id', 'task_id')
    )
    op.create_index(op.f('ix_task_notices_task_id'), 'task_notices', ['task_id'], unique=False)
    # ### end Alembic commands ###
    op.add_column('purchase_orders', sa.Column('planned_ship_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('planned_ship_date', sa.Date(), nullable=True))
    with op.batch_alter_table('notifications') as batch:
        batch.add_column(sa.Column('task_id', sa.String(36), nullable=True))
        batch.create_foreign_key('fk_notification_task', 'tasks', ['task_id'], ['id'])
        batch.create_index('ix_notifications_task_id', ['task_id'])


def downgrade():
    with op.batch_alter_table('notifications') as batch:
        batch.drop_index('ix_notifications_task_id')
        batch.drop_constraint('fk_notification_task', type_='foreignkey')
        batch.drop_column('task_id')
    for table, columns in [('shipments', ['planned_ship_date']), ('purchase_orders', ['ordered_at', 'planned_ship_date'])]:
        with op.batch_alter_table(table) as batch:
            for column in columns:
                batch.drop_column(column)
    for name in ['task_notices', 'task_operations', 'task_source_events', 'task_history', 'tasks', 'task_rule_schedules', 'task_rules']:
        op.drop_table(name)
