"""purchase shipments and inventory ledger"""
from alembic import op
import sqlalchemy as sa


revision = '9fa3ed5d01d2'
down_revision = 'cac0e1679f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inventory_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('reserved', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0 AND reserved >= 0 AND reserved <= quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'warehouse_id', 'product_id', name='uq_inventory_scope')
    )
    op.create_index(op.f('ix_inventory_balances_product_id'), 'inventory_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_store_id'), 'inventory_balances', ['store_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_warehouse_id'), 'inventory_balances', ['warehouse_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('reserved_delta', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reserved_after', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_id'), 'inventory_movements', ['reference_id'], unique=False)
    op.create_index('ix_movement_scope_time', 'inventory_movements', ['store_id', 'warehouse_id', 'created_at'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=2000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index('ix_purchase_status_expected', 'purchase_orders', ['status', 'expected_date'], unique=False)
    op.create_index('ix_purchase_store_created', 'purchase_orders', ['store_id', 'created_at'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('internal_sku', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('received_quantity', sa.BigInteger(), nullable=False),
    sa.Column('cancelled_quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0 AND received_quantity >= 0 AND cancelled_quantity >= 0 AND received_quantity + cancelled_quantity <= quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'product_id')
    )
    op.create_index(op.f('ix_purchase_lines_product_id'), 'purchase_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_purchase_order_id'), 'purchase_lines', ['purchase_order_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('source_warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('destination_warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('carrier', sa.String(length=120), nullable=False),
    sa.Column('tracking_number', sa.String(length=120), nullable=False),
    sa.Column('amazon_shipment_id', sa.String(length=120), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(purchase_order_id IS NULL) <> (source_warehouse_id IS NULL)'),
    sa.CheckConstraint('source_warehouse_id IS NULL OR source_warehouse_id <> destination_warehouse_id'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_shipment_status_expected', 'shipments', ['status', 'expected_date'], unique=False)
    op.create_index('ix_shipment_store_created', 'shipments', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_shipments_destination_warehouse_id'), 'shipments', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_shipments_purchase_order_id'), 'shipments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_shipments_source_warehouse_id'), 'shipments', ['source_warehouse_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_event_time', 'shipment_events', ['shipment_id', 'created_at'], unique=False)
    op.create_table('shipment_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_line_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('internal_sku', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('received_quantity', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('quantity > 0 AND received_quantity >= 0 AND received_quantity <= quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'product_id')
    )
    op.create_index(op.f('ix_shipment_lines_product_id'), 'shipment_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_lines_purchase_line_id'), 'shipment_lines', ['purchase_line_id'], unique=False)
    op.create_index(op.f('ix_shipment_lines_shipment_id'), 'shipment_lines', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_lines_shipment_id'), table_name='shipment_lines')
    op.drop_index(op.f('ix_shipment_lines_purchase_line_id'), table_name='shipment_lines')
    op.drop_index(op.f('ix_shipment_lines_product_id'), table_name='shipment_lines')
    op.drop_table('shipment_lines')
    op.drop_index('ix_shipment_event_time', table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_shipments_source_warehouse_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_purchase_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_destination_warehouse_id'), table_name='shipments')
    op.drop_index('ix_shipment_store_created', table_name='shipments')
    op.drop_index('ix_shipment_status_expected', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_purchase_lines_purchase_order_id'), table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_product_id'), table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index('ix_purchase_store_created', table_name='purchase_orders')
    op.drop_index('ix_purchase_status_expected', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_movement_scope_time', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_balances_warehouse_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_store_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_product_id'), table_name='inventory_balances')
    op.drop_table('inventory_balances')
    op.drop_table('warehouses')
    op.drop_table('supply_operations')
    # ### end Alembic commands ###
