"""Shared product catalog supplier quotes and source imports"""
from alembic import op
import sqlalchemy as sa


revision = 'cac0e1679f69'
down_revision = '465032443f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('internal_sku', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('specifications', sa.Text(), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('asin', sa.String(length=40), nullable=False),
    sa.Column('fnsku', sa.String(length=40), nullable=False),
    sa.Column('image_url', sa.String(length=2000), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('bullet_points', sa.JSON(), nullable=False),
    sa.Column('amazon_url', sa.String(length=2000), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('original_sale_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('review_notes', sa.JSON(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_sku')
    )
    op.create_index(op.f('ix_products_asin'), 'products', ['asin'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_fnsku'), 'products', ['fnsku'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_needs_review'), 'products', ['needs_review'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=400), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('payment_terms', sa.String(length=2000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name_key')
    )
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_table('product_imports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('price_unit', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('parsed_rows', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'file_hash', 'price_unit', name='uq_product_import_source'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_product_imports_owner_id'), 'product_imports', ['owner_id'], unique=False)
    op.create_table('supplier_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('packaging', sa.String(length=500), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_status', sa.String(length=20), nullable=False),
    sa.Column('includes_shipping', sa.Boolean(), nullable=True),
    sa.Column('includes_labeling', sa.Boolean(), nullable=True),
    sa.Column('labeling_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tiers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_quotes_is_active'), 'supplier_quotes', ['is_active'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_review_status'), 'supplier_quotes', ['review_status'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_supplier_id'), 'supplier_quotes', ['supplier_id'], unique=False)
    op.create_table('quote_products',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['supplier_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_products')
    op.drop_index(op.f('ix_supplier_quotes_supplier_id'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_review_status'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_is_active'), table_name='supplier_quotes')
    op.drop_table('supplier_quotes')
    op.drop_index(op.f('ix_product_imports_owner_id'), table_name='product_imports')
    op.drop_table('product_imports')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_needs_review'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_fnsku'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_asin'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
