"""amazon sales and advertising report imports"""
from alembic import op
import sqlalchemy as sa


revision = 'de1aefc77089'
down_revision = '9fa3ed5d01d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=36), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('parsed_rows', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('duplicate_count', sa.BigInteger(), nullable=False),
    sa.Column('source_total', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_report_import_store_time', 'report_imports', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_report_imports_store_id'), 'report_imports', ['store_id'], unique=False)
    op.create_table('ad_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('natural_key', sa.String(length=64), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('source_row', sa.BigInteger(), nullable=False),
    sa.Column('latest_report_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('campaign', sa.String(length=500), nullable=False),
    sa.Column('ad_group', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('asin', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('attributed_sales', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('orders', sa.BigInteger(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.CheckConstraint('start_date <= end_date AND impressions >= 0 AND clicks >= 0 AND spend >= 0'),
    sa.ForeignKeyConstraint(['import_id'], ['report_imports.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'natural_key', name='uq_ad_record_key')
    )
    op.create_index(op.f('ix_ad_records_import_id'), 'ad_records', ['import_id'], unique=False)
    op.create_index('ix_ad_store_identity_period', 'ad_records', ['store_id', 'identity_key', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_ad_store_period', 'ad_records', ['store_id', 'start_date', 'end_date'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('natural_key', sa.String(length=64), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('source_row', sa.BigInteger(), nullable=False),
    sa.Column('amazon_order_id', sa.String(length=120), nullable=False),
    sa.Column('sales_channel', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('asin', sa.String(length=120), nullable=False),
    sa.Column('product_name', sa.String(length=2000), nullable=False),
    sa.Column('order_status', sa.String(length=120), nullable=False),
    sa.Column('item_status', sa.String(length=120), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['import_id'], ['report_imports.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'natural_key', name='uq_sales_record_key')
    )
    op.create_index(op.f('ix_sales_records_amazon_order_id'), 'sales_records', ['amazon_order_id'], unique=False)
    op.create_index(op.f('ix_sales_records_import_id'), 'sales_records', ['import_id'], unique=False)
    op.create_index('ix_sales_store_date', 'sales_records', ['store_id', 'purchase_date'], unique=False)
    op.create_index('ix_sales_store_sku', 'sales_records', ['store_id', 'sku'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_store_sku', table_name='sales_records')
    op.drop_index('ix_sales_store_date', table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_import_id'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_amazon_order_id'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index('ix_ad_store_period', table_name='ad_records')
    op.drop_index('ix_ad_store_identity_period', table_name='ad_records')
    op.drop_index(op.f('ix_ad_records_import_id'), table_name='ad_records')
    op.drop_table('ad_records')
    op.drop_index(op.f('ix_report_imports_store_id'), table_name='report_imports')
    op.drop_index('ix_report_import_store_time', table_name='report_imports')
    op.drop_table('report_imports')
    # ### end Alembic commands ###
